//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsModels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleTag
    {
        public int id { get; set; }
        public Nullable<int> articleId { get; set; }
        public Nullable<int> tagId { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
